name: "Utilities"
description: "Contains utilities"

inputs:
  install_taskfile:
    description: "install taskfile if true"
    default: "true"
  taskfile_version:
    description: "specify the version of taskfile"
    default: "3.52.0"

runs:
  using: composite
  steps:
    - name: "Echo Input vars"
      shell: bash
      run: |
        echo "install taskfile = ${{ inputs.install_taskfile }}"
        echo "Taskfile version = ${{ inputs.taskfile_version }}"
    - name: "Install Taskfile"
      if: ${{ inputs.install_taskfile == 'true' }}
      uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e
      with:
        version: ${{ inputs.taskfile_version }}
