name: "Close stale issues"

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale-issue-close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93
        with:
          days-before-stale: 30
